# -*- coding: utf-8 -*-
"""FOODIE$_generatecossim.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ECal3YrKCy240iBwKr4VvzFKCdHXQcyM
"""

import pandas as pd
import numpy as np
from numpy import linalg as LA
from sklearn.feature_extraction.text import TfidfVectorizer
import re

def rocchio_results(df, query, feedback):
  reviews = df['comments'].tolist()
  tfidf_vectorizer = TfidfVectorizer()
  tfidf_matrix = tfidf_vectorizer.fit_transform(reviews).toarray() # 3060 x 6506 matrix
  tfidf_matrix # currently very sparse - an option is to make it dense but more costly in memory

  query_tfidf = tfidf_vectorizer.transform([query]).toarray()

  types = set()

  for entry in df["type"]:
    temp = re.findall(r'[a-z]+', entry.lower())
    for val in temp:
      types.add(val)


  qtokens = re.findall(r'[a-z]+', query.lower())
  qtokens = set(qtokens)
  qtypes = set()
  for t in qtokens:
    if t in types:
      qtypes.add(t)

    relevant_docs = feedback # list of relevant document indices

    non_relevant_docs = []  # list of non-relevant document indices
    #currently nothing because not at that level yet

    # Extract relevant and non-relevant document indices from feedback
    #for entry in feedback:
     #   if entry['liked']:
      #      relevant_docs.append(entry['restaurant_id'])
       # else:
        #    non_relevant_docs.append(entry['restaurant_id'])
        
    alpha = 1
    beta = 0.75
    gamma = 0.25

    query_vector = alpha * query_tfidf

    if relevant_docs:
        relevant_vectors = tfidf_matrix[relevant_docs]
        relevant_vector = np.mean(relevant_vectors, axis=0)
        query_vector += beta * relevant_vector

    if non_relevant_docs:
        non_relevant_vectors = tfidf_matrix[non_relevant_docs]
        non_relevant_vector = np.mean(non_relevant_vectors, axis=0)
        query_vector -= gamma * non_relevant_vector

    rocchio_cossims = []
    for i in range(len(tfidf_matrix)):
        doc = tfidf_matrix[i]
        mov1norm = np.sqrt(np.sum(np.square(query_vector)))
        mov2norm = np.sqrt(np.sum(np.square(doc)))
        num = np.dot(query_vector, doc)
        den = mov1norm * mov2norm
        if den == 0:
            rocchio_cossims.append((i, 0))
        else:
            temp = num / den
            rocchio_cossims.append((i, temp))

    rocchio_cossims_sorted = sorted(rocchio_cossims, key=lambda x: x[1], reverse=True)

    top_restaurants = []
    num = len(rocchio_cossims_sorted)

    for i in range(len(rocchio_cossims_sorted)):
        top_restaurants.append(df.at[rocchio_cossims_sorted[i][0], 'name'])

    return top_restaurants